defaults:
  - autoencoder: stable_vae
  - backbone: udit
  - _self_

cfg_drop_ratio: 0.2

backbone:
  embed_dim: 1024
  depth: 24
  num_heads: 16

_target_: models.flow_matching.SingleTaskCrossAttentionAudioFlowMatching
content_encoder:
  _target_: models.content_encoder.content_encoder.ContentEncoder
  embed_dim: 1024
  text_encoder:
    _target_: models.content_encoder.text_encoder.T5TextEncoder
    model_name: google/flan-t5-large
    embed_dim: 1024
 
